//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DelegationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DelegationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="delay" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="extension_delay" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="urgent_procedure" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DelegationType", propOrder = {
    "delay",
    "extensionDelay",
    "urgentProcedure"
})
public class DelegationType {

    protected int delay;
    @XmlElement(name = "extension_delay")
    protected Integer extensionDelay;
    @XmlElement(name = "urgent_procedure")
    protected boolean urgentProcedure;

    /**
     * Gets the value of the delay property.
     * 
     */
    public int getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     */
    public void setDelay(int value) {
        this.delay = value;
    }

    /**
     * Gets the value of the extensionDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExtensionDelay() {
        return extensionDelay;
    }

    /**
     * Sets the value of the extensionDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExtensionDelay(Integer value) {
        this.extensionDelay = value;
    }

    /**
     * Gets the value of the urgentProcedure property.
     * 
     */
    public boolean isUrgentProcedure() {
        return urgentProcedure;
    }

    /**
     * Sets the value of the urgentProcedure property.
     * 
     */
    public void setUrgentProcedure(boolean value) {
        this.urgentProcedure = value;
    }

}
