//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Extension for an expression.
 * 			
 * 
 * <p>Java class for ExpressionExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpressionExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_expression_extension_base"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="language_authentic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="estimated_transmission_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpressionExtensionType", propOrder = {
    "languageAuthentic",
    "estimatedTransmissionDateTime"
})
public class ExpressionExtensionType
    extends TExpressionExtensionBase
{

    @XmlElement(name = "language_authentic")
    protected Boolean languageAuthentic;
    @XmlElement(name = "estimated_transmission_date_time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedTransmissionDateTime;

    /**
     * Gets the value of the languageAuthentic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLanguageAuthentic() {
        return languageAuthentic;
    }

    /**
     * Sets the value of the languageAuthentic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLanguageAuthentic(Boolean value) {
        this.languageAuthentic = value;
    }

    /**
     * Gets the value of the estimatedTransmissionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedTransmissionDateTime() {
        return estimatedTransmissionDateTime;
    }

    /**
     * Sets the value of the estimatedTransmissionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedTransmissionDateTime(XMLGregorianCalendar value) {
        this.estimatedTransmissionDateTime = value;
    }

}
