//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Extension for a manifestation.
 * 			
 * 
 * <p>Java class for ManifestationExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManifestationExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_manifestation_extension_base"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="last_sequence" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManifestationExtensionType", propOrder = {
    "lastSequence"
})
public class ManifestationExtensionType
    extends TManifestationExtensionBase
{

    @XmlElement(name = "last_sequence", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lastSequence;

    /**
     * Gets the value of the lastSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastSequence() {
        return lastSequence;
    }

    /**
     * Sets the value of the lastSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastSequence(BigInteger value) {
        this.lastSequence = value;
    }

}
