//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Extension for a procedure.
 * 			
 * 
 * <p>Java class for ProcedureExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcedureExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_procedure_extension_base"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subsidiarity_proportionality_application" type="{urn:eu:ec:cm:common:extensions:v11}SubsidiarityProportionalityApplicationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcedureExtensionType", propOrder = {
    "subsidiarityProportionalityApplication"
})
public class ProcedureExtensionType
    extends TProcedureExtensionBase
{

    @XmlElement(name = "subsidiarity_proportionality_application")
    protected SubsidiarityProportionalityApplicationType subsidiarityProportionalityApplication;

    /**
     * Gets the value of the subsidiarityProportionalityApplication property.
     * 
     * @return
     *     possible object is
     *     {@link SubsidiarityProportionalityApplicationType }
     *     
     */
    public SubsidiarityProportionalityApplicationType getSubsidiarityProportionalityApplication() {
        return subsidiarityProportionalityApplication;
    }

    /**
     * Sets the value of the subsidiarityProportionalityApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsidiarityProportionalityApplicationType }
     *     
     */
    public void setSubsidiarityProportionalityApplication(SubsidiarityProportionalityApplicationType value) {
        this.subsidiarityProportionalityApplication = value;
    }

}
