//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Application of the principles of subsidiarity and proportionality.
 * 
 * <p>Java class for SubsidiarityProportionalityApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubsidiarityProportionalityApplicationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="competence_type" type="{urn:eu:ec:cm:common:extensions:v11}ConstantType"/&gt;
 *         &lt;element name="legal_reference" type="{http://publications.europa.eu/resource/core-metadata}t_legal_procedure" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubsidiarityProportionalityApplicationType", propOrder = {
    "competenceType",
    "legalReference"
})
public class SubsidiarityProportionalityApplicationType {

    @XmlElement(name = "competence_type", required = true)
    protected String competenceType;
    @XmlElement(name = "legal_reference", required = true)
    protected List<TLegalProcedure> legalReference;

    /**
     * Gets the value of the competenceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompetenceType() {
        return competenceType;
    }

    /**
     * Sets the value of the competenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompetenceType(String value) {
        this.competenceType = value;
    }

    /**
     * Gets the value of the legalReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legalReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLegalProcedure }
     * 
     * 
     */
    public List<TLegalProcedure> getLegalReference() {
        if (legalReference == null) {
            legalReference = new ArrayList<TLegalProcedure>();
        }
        return this.legalReference;
    }

}
