//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_corporatebody.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_corporatebody"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACER"/&gt;
 *     &lt;enumeration value="ACP"/&gt;
 *     &lt;enumeration value="ACP-EU_JA"/&gt;
 *     &lt;enumeration value="ACP-EU_JPA"/&gt;
 *     &lt;enumeration value="ACP_AMB"/&gt;
 *     &lt;enumeration value="ACP_CDE"/&gt;
 *     &lt;enumeration value="ACP_MIN"/&gt;
 *     &lt;enumeration value="AGRI"/&gt;
 *     &lt;enumeration value="AIDCO"/&gt;
 *     &lt;enumeration value="ARTEMIS"/&gt;
 *     &lt;enumeration value="AUDIT"/&gt;
 *     &lt;enumeration value="BDS"/&gt;
 *     &lt;enumeration value="BEPA"/&gt;
 *     &lt;enumeration value="BERD"/&gt;
 *     &lt;enumeration value="BEREC"/&gt;
 *     &lt;enumeration value="BIS"/&gt;
 *     &lt;enumeration value="BSI"/&gt;
 *     &lt;enumeration value="BTB"/&gt;
 *     &lt;enumeration value="BTL"/&gt;
 *     &lt;enumeration value="BUDG"/&gt;
 *     &lt;enumeration value="CBNM"/&gt;
 *     &lt;enumeration value="CDT"/&gt;
 *     &lt;enumeration value="CEDEFOP"/&gt;
 *     &lt;enumeration value="CEPOL"/&gt;
 *     &lt;enumeration value="CFCA"/&gt;
 *     &lt;enumeration value="CFI"/&gt;
 *     &lt;enumeration value="CJ"/&gt;
 *     &lt;enumeration value="CLIMA"/&gt;
 *     &lt;enumeration value="CMT_CONC"/&gt;
 *     &lt;enumeration value="CMT_CONJOIN"/&gt;
 *     &lt;enumeration value="CMT_CONS"/&gt;
 *     &lt;enumeration value="CMT_COOP"/&gt;
 *     &lt;enumeration value="CMT_COOP_CUSTOM"/&gt;
 *     &lt;enumeration value="CMT_JOIN"/&gt;
 *     &lt;enumeration value="CMT_MIX"/&gt;
 *     &lt;enumeration value="CMT_MON"/&gt;
 *     &lt;enumeration value="CMT_PARIT"/&gt;
 *     &lt;enumeration value="CNECT"/&gt;
 *     &lt;enumeration value="COM"/&gt;
 *     &lt;enumeration value="COMMU"/&gt;
 *     &lt;enumeration value="COMP"/&gt;
 *     &lt;enumeration value="CONSIL"/&gt;
 *     &lt;enumeration value="COR"/&gt;
 *     &lt;enumeration value="COUN_ASS"/&gt;
 *     &lt;enumeration value="COUN_COOP"/&gt;
 *     &lt;enumeration value="COUN_JOIN"/&gt;
 *     &lt;enumeration value="COURT_NAT"/&gt;
 *     &lt;enumeration value="COU_EUR"/&gt;
 *     &lt;enumeration value="CPP"/&gt;
 *     &lt;enumeration value="CPVO"/&gt;
 *     &lt;enumeration value="CST"/&gt;
 *     &lt;enumeration value="CURIA"/&gt;
 *     &lt;enumeration value="CYBER"/&gt;
 *     &lt;enumeration value="D9D"/&gt;
 *     &lt;enumeration value="D9P"/&gt;
 *     &lt;enumeration value="DEE"/&gt;
 *     &lt;enumeration value="DEL_ACC"/&gt;
 *     &lt;enumeration value="DEV"/&gt;
 *     &lt;enumeration value="DEVCO"/&gt;
 *     &lt;enumeration value="DG01"/&gt;
 *     &lt;enumeration value="DG01A"/&gt;
 *     &lt;enumeration value="DG01B"/&gt;
 *     &lt;enumeration value="DG02"/&gt;
 *     &lt;enumeration value="DG03"/&gt;
 *     &lt;enumeration value="DG07"/&gt;
 *     &lt;enumeration value="DG10"/&gt;
 *     &lt;enumeration value="DG15"/&gt;
 *     &lt;enumeration value="DG17"/&gt;
 *     &lt;enumeration value="DG18"/&gt;
 *     &lt;enumeration value="DG18_DC"/&gt;
 *     &lt;enumeration value="DG23"/&gt;
 *     &lt;enumeration value="DG5_DH"/&gt;
 *     &lt;enumeration value="DGT"/&gt;
 *     &lt;enumeration value="DIGIT"/&gt;
 *     &lt;enumeration value="EAC"/&gt;
 *     &lt;enumeration value="EACEA"/&gt;
 *     &lt;enumeration value="EACI"/&gt;
 *     &lt;enumeration value="EAEC"/&gt;
 *     &lt;enumeration value="EAEC_COM"/&gt;
 *     &lt;enumeration value="EAEC_COUN"/&gt;
 *     &lt;enumeration value="EAEC_ES"/&gt;
 *     &lt;enumeration value="EAHC"/&gt;
 *     &lt;enumeration value="EAPH"/&gt;
 *     &lt;enumeration value="EAR"/&gt;
 *     &lt;enumeration value="EAS"/&gt;
 *     &lt;enumeration value="EASA"/&gt;
 *     &lt;enumeration value="EASO"/&gt;
 *     &lt;enumeration value="EBA"/&gt;
 *     &lt;enumeration value="EC"/&gt;
 *     &lt;enumeration value="ECA"/&gt;
 *     &lt;enumeration value="ECB"/&gt;
 *     &lt;enumeration value="ECDC"/&gt;
 *     &lt;enumeration value="ECFIN"/&gt;
 *     &lt;enumeration value="ECHA"/&gt;
 *     &lt;enumeration value="ECHO"/&gt;
 *     &lt;enumeration value="ECHR"/&gt;
 *     &lt;enumeration value="ECOSOC"/&gt;
 *     &lt;enumeration value="ECSC"/&gt;
 *     &lt;enumeration value="ECSC_CJ"/&gt;
 *     &lt;enumeration value="ECSC_CMIN"/&gt;
 *     &lt;enumeration value="ECSC_CMTCSL"/&gt;
 *     &lt;enumeration value="ECSC_HA"/&gt;
 *     &lt;enumeration value="ECSC_PRESS"/&gt;
 *     &lt;enumeration value="ECSC_SG"/&gt;
 *     &lt;enumeration value="EDA"/&gt;
 *     &lt;enumeration value="EDPS"/&gt;
 *     &lt;enumeration value="EEA"/&gt;
 *     &lt;enumeration value="EEAREA"/&gt;
 *     &lt;enumeration value="EEAREA_MS"/&gt;
 *     &lt;enumeration value="EEAS"/&gt;
 *     &lt;enumeration value="EEC"/&gt;
 *     &lt;enumeration value="EEC_COM"/&gt;
 *     &lt;enumeration value="EEC_COUN"/&gt;
 *     &lt;enumeration value="EEC_ES"/&gt;
 *     &lt;enumeration value="EESC"/&gt;
 *     &lt;enumeration value="EFC"/&gt;
 *     &lt;enumeration value="EFSA"/&gt;
 *     &lt;enumeration value="EFTA"/&gt;
 *     &lt;enumeration value="EFTA_COURT"/&gt;
 *     &lt;enumeration value="EFTA_MS"/&gt;
 *     &lt;enumeration value="EFTA_SEC"/&gt;
 *     &lt;enumeration value="EFTA_STC"/&gt;
 *     &lt;enumeration value="EFTA_SUC"/&gt;
 *     &lt;enumeration value="EGSA"/&gt;
 *     &lt;enumeration value="EIB"/&gt;
 *     &lt;enumeration value="EIB_GOV"/&gt;
 *     &lt;enumeration value="EIF"/&gt;
 *     &lt;enumeration value="EIGE"/&gt;
 *     &lt;enumeration value="EIOPA"/&gt;
 *     &lt;enumeration value="EIT"/&gt;
 *     &lt;enumeration value="ELARG"/&gt;
 *     &lt;enumeration value="EMBL"/&gt;
 *     &lt;enumeration value="EMCDDA"/&gt;
 *     &lt;enumeration value="EMEA"/&gt;
 *     &lt;enumeration value="EMI"/&gt;
 *     &lt;enumeration value="EMPL"/&gt;
 *     &lt;enumeration value="EMSA"/&gt;
 *     &lt;enumeration value="ENER"/&gt;
 *     &lt;enumeration value="ENIAC"/&gt;
 *     &lt;enumeration value="ENISA"/&gt;
 *     &lt;enumeration value="ENTR"/&gt;
 *     &lt;enumeration value="ENV"/&gt;
 *     &lt;enumeration value="EP"/&gt;
 *     &lt;enumeration value="EPOFF"/&gt;
 *     &lt;enumeration value="EPORG"/&gt;
 *     &lt;enumeration value="EPSO"/&gt;
 *     &lt;enumeration value="EP_AFCO"/&gt;
 *     &lt;enumeration value="EP_AFET"/&gt;
 *     &lt;enumeration value="EP_AGRI"/&gt;
 *     &lt;enumeration value="EP_BUDG"/&gt;
 *     &lt;enumeration value="EP_CMT"/&gt;
 *     &lt;enumeration value="EP_COMMU"/&gt;
 *     &lt;enumeration value="EP_CONT"/&gt;
 *     &lt;enumeration value="EP_CRIM"/&gt;
 *     &lt;enumeration value="EP_CRIS"/&gt;
 *     &lt;enumeration value="EP_CULT"/&gt;
 *     &lt;enumeration value="EP_DELCON"/&gt;
 *     &lt;enumeration value="EP_DEVE"/&gt;
 *     &lt;enumeration value="EP_DROI"/&gt;
 *     &lt;enumeration value="EP_ECON"/&gt;
 *     &lt;enumeration value="EP_EMPL"/&gt;
 *     &lt;enumeration value="EP_ENVI"/&gt;
 *     &lt;enumeration value="EP_EXTERN_POL"/&gt;
 *     &lt;enumeration value="EP_FEMM"/&gt;
 *     &lt;enumeration value="EP_FINANCE"/&gt;
 *     &lt;enumeration value="EP_GROUP_ALDE"/&gt;
 *     &lt;enumeration value="EP_GROUP_ECR"/&gt;
 *     &lt;enumeration value="EP_GROUP_EFD"/&gt;
 *     &lt;enumeration value="EP_GROUP_EPP"/&gt;
 *     &lt;enumeration value="EP_GROUP_GREEN_EFA"/&gt;
 *     &lt;enumeration value="EP_GROUP_GUE_NGL"/&gt;
 *     &lt;enumeration value="EP_GROUP_SD"/&gt;
 *     &lt;enumeration value="EP_IMCO"/&gt;
 *     &lt;enumeration value="EP_IMMU"/&gt;
 *     &lt;enumeration value="EP_INFRA_LOGIS"/&gt;
 *     &lt;enumeration value="EP_INNOV"/&gt;
 *     &lt;enumeration value="EP_INQWOM"/&gt;
 *     &lt;enumeration value="EP_INTA"/&gt;
 *     &lt;enumeration value="EP_INTERNAL_POL"/&gt;
 *     &lt;enumeration value="EP_INTERPRET"/&gt;
 *     &lt;enumeration value="EP_ITRE"/&gt;
 *     &lt;enumeration value="EP_JURI"/&gt;
 *     &lt;enumeration value="EP_LIBE"/&gt;
 *     &lt;enumeration value="EP_PECH"/&gt;
 *     &lt;enumeration value="EP_PERS"/&gt;
 *     &lt;enumeration value="EP_PETI"/&gt;
 *     &lt;enumeration value="EP_POLI"/&gt;
 *     &lt;enumeration value="EP_PRES"/&gt;
 *     &lt;enumeration value="EP_REGI"/&gt;
 *     &lt;enumeration value="EP_SEDE"/&gt;
 *     &lt;enumeration value="EP_SG"/&gt;
 *     &lt;enumeration value="EP_SURE"/&gt;
 *     &lt;enumeration value="EP_TRAN"/&gt;
 *     &lt;enumeration value="EP_TRANSL"/&gt;
 *     &lt;enumeration value="ERA"/&gt;
 *     &lt;enumeration value="ERC"/&gt;
 *     &lt;enumeration value="ESA"/&gt;
 *     &lt;enumeration value="ESCB"/&gt;
 *     &lt;enumeration value="ESM"/&gt;
 *     &lt;enumeration value="ESMA"/&gt;
 *     &lt;enumeration value="ESRB"/&gt;
 *     &lt;enumeration value="ESTAT"/&gt;
 *     &lt;enumeration value="ETF"/&gt;
 *     &lt;enumeration value="EUISS"/&gt;
 *     &lt;enumeration value="EUMS"/&gt;
 *     &lt;enumeration value="EUMS10"/&gt;
 *     &lt;enumeration value="EUMS12"/&gt;
 *     &lt;enumeration value="EUMS15"/&gt;
 *     &lt;enumeration value="EUMS25"/&gt;
 *     &lt;enumeration value="EUMS27"/&gt;
 *     &lt;enumeration value="EUMS6"/&gt;
 *     &lt;enumeration value="EUMS9"/&gt;
 *     &lt;enumeration value="EUMS_EURO11"/&gt;
 *     &lt;enumeration value="EUMS_EURO12"/&gt;
 *     &lt;enumeration value="EUMS_EURO13"/&gt;
 *     &lt;enumeration value="EUMS_EURO15"/&gt;
 *     &lt;enumeration value="EUMS_EURO16"/&gt;
 *     &lt;enumeration value="EUMS_EURO17"/&gt;
 *     &lt;enumeration value="EUMS_NONEURO10"/&gt;
 *     &lt;enumeration value="EUMS_NONEURO11"/&gt;
 *     &lt;enumeration value="EUMS_NONEURO12"/&gt;
 *     &lt;enumeration value="EUMS_NONEURO14"/&gt;
 *     &lt;enumeration value="EUMS_NONEURO3"/&gt;
 *     &lt;enumeration value="EUMS_NONEURO4"/&gt;
 *     &lt;enumeration value="EURAG"/&gt;
 *     &lt;enumeration value="EURATOM"/&gt;
 *     &lt;enumeration value="EURCOM"/&gt;
 *     &lt;enumeration value="EURCOU"/&gt;
 *     &lt;enumeration value="EURCOU_PRES"/&gt;
 *     &lt;enumeration value="EUROCONTROL"/&gt;
 *     &lt;enumeration value="EUROFOUND"/&gt;
 *     &lt;enumeration value="EUROJUST"/&gt;
 *     &lt;enumeration value="EURONEST"/&gt;
 *     &lt;enumeration value="EUROPOL"/&gt;
 *     &lt;enumeration value="EURUN"/&gt;
 *     &lt;enumeration value="EUR_CONVENTON"/&gt;
 *     &lt;enumeration value="EUSC"/&gt;
 *     &lt;enumeration value="FAO"/&gt;
 *     &lt;enumeration value="FCH"/&gt;
 *     &lt;enumeration value="FPI"/&gt;
 *     &lt;enumeration value="FRA"/&gt;
 *     &lt;enumeration value="FRONTEX"/&gt;
 *     &lt;enumeration value="FSU"/&gt;
 *     &lt;enumeration value="FUSEN"/&gt;
 *     &lt;enumeration value="GATT"/&gt;
 *     &lt;enumeration value="GCEU"/&gt;
 *     &lt;enumeration value="GIW"/&gt;
 *     &lt;enumeration value="GOVREP"/&gt;
 *     &lt;enumeration value="HOME"/&gt;
 *     &lt;enumeration value="HR"/&gt;
 *     &lt;enumeration value="HRUFASP"/&gt;
 *     &lt;enumeration value="IAEA"/&gt;
 *     &lt;enumeration value="IAS"/&gt;
 *     &lt;enumeration value="IBWM"/&gt;
 *     &lt;enumeration value="ICAO"/&gt;
 *     &lt;enumeration value="ICCS"/&gt;
 *     &lt;enumeration value="ICES"/&gt;
 *     &lt;enumeration value="ICRC"/&gt;
 *     &lt;enumeration value="IDA"/&gt;
 *     &lt;enumeration value="IEEA"/&gt;
 *     &lt;enumeration value="IES"/&gt;
 *     &lt;enumeration value="IGS"/&gt;
 *     &lt;enumeration value="IHCP"/&gt;
 *     &lt;enumeration value="ILO"/&gt;
 *     &lt;enumeration value="IMI"/&gt;
 *     &lt;enumeration value="INFSO"/&gt;
 *     &lt;enumeration value="INRO"/&gt;
 *     &lt;enumeration value="INTERPOL"/&gt;
 *     &lt;enumeration value="IPSC"/&gt;
 *     &lt;enumeration value="IRSG"/&gt;
 *     &lt;enumeration value="ISOSUGAR"/&gt;
 *     &lt;enumeration value="JLS"/&gt;
 *     &lt;enumeration value="JRC"/&gt;
 *     &lt;enumeration value="JRCGEEL"/&gt;
 *     &lt;enumeration value="JRCISP"/&gt;
 *     &lt;enumeration value="JRCKARLS"/&gt;
 *     &lt;enumeration value="JRCPETT"/&gt;
 *     &lt;enumeration value="JRCSEV"/&gt;
 *     &lt;enumeration value="JUSTI"/&gt;
 *     &lt;enumeration value="MARE"/&gt;
 *     &lt;enumeration value="MARKT"/&gt;
 *     &lt;enumeration value="MOVE"/&gt;
 *     &lt;enumeration value="NATO"/&gt;
 *     &lt;enumeration value="NP"/&gt;
 *     &lt;enumeration value="OAMI"/&gt;
 *     &lt;enumeration value="OCHA"/&gt;
 *     &lt;enumeration value="ODCR"/&gt;
 *     &lt;enumeration value="OIB"/&gt;
 *     &lt;enumeration value="OIL"/&gt;
 *     &lt;enumeration value="OLAF"/&gt;
 *     &lt;enumeration value="OMB"/&gt;
 *     &lt;enumeration value="OSHA"/&gt;
 *     &lt;enumeration value="PMO"/&gt;
 *     &lt;enumeration value="PRESS"/&gt;
 *     &lt;enumeration value="PRESS_COMMUN"/&gt;
 *     &lt;enumeration value="PUBL"/&gt;
 *     &lt;enumeration value="RCN"/&gt;
 *     &lt;enumeration value="REA"/&gt;
 *     &lt;enumeration value="REGIO"/&gt;
 *     &lt;enumeration value="RELEX"/&gt;
 *     &lt;enumeration value="RTD"/&gt;
 *     &lt;enumeration value="SANCO"/&gt;
 *     &lt;enumeration value="SCIC"/&gt;
 *     &lt;enumeration value="SCR"/&gt;
 *     &lt;enumeration value="SESAR"/&gt;
 *     &lt;enumeration value="SG"/&gt;
 *     &lt;enumeration value="SJ"/&gt;
 *     &lt;enumeration value="SJ_COMMUN"/&gt;
 *     &lt;enumeration value="SKY"/&gt;
 *     &lt;enumeration value="SPP"/&gt;
 *     &lt;enumeration value="STAT_COMMUN"/&gt;
 *     &lt;enumeration value="TASKF"/&gt;
 *     &lt;enumeration value="TAXUD"/&gt;
 *     &lt;enumeration value="TENTEA"/&gt;
 *     &lt;enumeration value="TRADE"/&gt;
 *     &lt;enumeration value="TREN"/&gt;
 *     &lt;enumeration value="UNECE"/&gt;
 *     &lt;enumeration value="UNEP"/&gt;
 *     &lt;enumeration value="UNESCO"/&gt;
 *     &lt;enumeration value="UNHCR"/&gt;
 *     &lt;enumeration value="UNICEF"/&gt;
 *     &lt;enumeration value="UNO"/&gt;
 *     &lt;enumeration value="UNRWA"/&gt;
 *     &lt;enumeration value="US_AEC"/&gt;
 *     &lt;enumeration value="WFP"/&gt;
 *     &lt;enumeration value="WHO"/&gt;
 *     &lt;enumeration value="WTO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "t_corporatebody", namespace = "http://publications.europa.eu/resource/corporatebodies/")
@XmlEnum
public enum TCorporatebody {

    ACER("ACER"),
    ACP("ACP"),
    @XmlEnumValue("ACP-EU_JA")
    ACP_EU_JA("ACP-EU_JA"),
    @XmlEnumValue("ACP-EU_JPA")
    ACP_EU_JPA("ACP-EU_JPA"),
    ACP_AMB("ACP_AMB"),
    ACP_CDE("ACP_CDE"),
    ACP_MIN("ACP_MIN"),
    AGRI("AGRI"),
    AIDCO("AIDCO"),
    ARTEMIS("ARTEMIS"),
    AUDIT("AUDIT"),
    BDS("BDS"),
    BEPA("BEPA"),
    BERD("BERD"),
    BEREC("BEREC"),
    BIS("BIS"),
    BSI("BSI"),
    BTB("BTB"),
    BTL("BTL"),
    BUDG("BUDG"),
    CBNM("CBNM"),
    CDT("CDT"),
    CEDEFOP("CEDEFOP"),
    CEPOL("CEPOL"),
    CFCA("CFCA"),
    CFI("CFI"),
    CJ("CJ"),
    CLIMA("CLIMA"),
    CMT_CONC("CMT_CONC"),
    CMT_CONJOIN("CMT_CONJOIN"),
    CMT_CONS("CMT_CONS"),
    CMT_COOP("CMT_COOP"),
    CMT_COOP_CUSTOM("CMT_COOP_CUSTOM"),
    CMT_JOIN("CMT_JOIN"),
    CMT_MIX("CMT_MIX"),
    CMT_MON("CMT_MON"),
    CMT_PARIT("CMT_PARIT"),
    CNECT("CNECT"),
    COM("COM"),
    COMMU("COMMU"),
    COMP("COMP"),
    CONSIL("CONSIL"),
    COR("COR"),
    COUN_ASS("COUN_ASS"),
    COUN_COOP("COUN_COOP"),
    COUN_JOIN("COUN_JOIN"),
    COURT_NAT("COURT_NAT"),
    COU_EUR("COU_EUR"),
    CPP("CPP"),
    CPVO("CPVO"),
    CST("CST"),
    CURIA("CURIA"),
    CYBER("CYBER"),
    @XmlEnumValue("D9D")
    D_9_D("D9D"),
    @XmlEnumValue("D9P")
    D_9_P("D9P"),
    DEE("DEE"),
    DEL_ACC("DEL_ACC"),
    DEV("DEV"),
    DEVCO("DEVCO"),
    @XmlEnumValue("DG01")
    DG_01("DG01"),
    @XmlEnumValue("DG01A")
    DG_01_A("DG01A"),
    @XmlEnumValue("DG01B")
    DG_01_B("DG01B"),
    @XmlEnumValue("DG02")
    DG_02("DG02"),
    @XmlEnumValue("DG03")
    DG_03("DG03"),
    @XmlEnumValue("DG07")
    DG_07("DG07"),
    @XmlEnumValue("DG10")
    DG_10("DG10"),
    @XmlEnumValue("DG15")
    DG_15("DG15"),
    @XmlEnumValue("DG17")
    DG_17("DG17"),
    @XmlEnumValue("DG18")
    DG_18("DG18"),
    @XmlEnumValue("DG18_DC")
    DG_18_DC("DG18_DC"),
    @XmlEnumValue("DG23")
    DG_23("DG23"),
    @XmlEnumValue("DG5_DH")
    DG_5_DH("DG5_DH"),
    DGT("DGT"),
    DIGIT("DIGIT"),
    EAC("EAC"),
    EACEA("EACEA"),
    EACI("EACI"),
    EAEC("EAEC"),
    EAEC_COM("EAEC_COM"),
    EAEC_COUN("EAEC_COUN"),
    EAEC_ES("EAEC_ES"),
    EAHC("EAHC"),
    EAPH("EAPH"),
    EAR("EAR"),
    EAS("EAS"),
    EASA("EASA"),
    EASO("EASO"),
    EBA("EBA"),
    EC("EC"),
    ECA("ECA"),
    ECB("ECB"),
    ECDC("ECDC"),
    ECFIN("ECFIN"),
    ECHA("ECHA"),
    ECHO("ECHO"),
    ECHR("ECHR"),
    ECOSOC("ECOSOC"),
    ECSC("ECSC"),
    ECSC_CJ("ECSC_CJ"),
    ECSC_CMIN("ECSC_CMIN"),
    ECSC_CMTCSL("ECSC_CMTCSL"),
    ECSC_HA("ECSC_HA"),
    ECSC_PRESS("ECSC_PRESS"),
    ECSC_SG("ECSC_SG"),
    EDA("EDA"),
    EDPS("EDPS"),
    EEA("EEA"),
    EEAREA("EEAREA"),
    EEAREA_MS("EEAREA_MS"),
    EEAS("EEAS"),
    EEC("EEC"),
    EEC_COM("EEC_COM"),
    EEC_COUN("EEC_COUN"),
    EEC_ES("EEC_ES"),
    EESC("EESC"),
    EFC("EFC"),
    EFSA("EFSA"),
    EFTA("EFTA"),
    EFTA_COURT("EFTA_COURT"),
    EFTA_MS("EFTA_MS"),
    EFTA_SEC("EFTA_SEC"),
    EFTA_STC("EFTA_STC"),
    EFTA_SUC("EFTA_SUC"),
    EGSA("EGSA"),
    EIB("EIB"),
    EIB_GOV("EIB_GOV"),
    EIF("EIF"),
    EIGE("EIGE"),
    EIOPA("EIOPA"),
    EIT("EIT"),
    ELARG("ELARG"),
    EMBL("EMBL"),
    EMCDDA("EMCDDA"),
    EMEA("EMEA"),
    EMI("EMI"),
    EMPL("EMPL"),
    EMSA("EMSA"),
    ENER("ENER"),
    ENIAC("ENIAC"),
    ENISA("ENISA"),
    ENTR("ENTR"),
    ENV("ENV"),
    EP("EP"),
    EPOFF("EPOFF"),
    EPORG("EPORG"),
    EPSO("EPSO"),
    EP_AFCO("EP_AFCO"),
    EP_AFET("EP_AFET"),
    EP_AGRI("EP_AGRI"),
    EP_BUDG("EP_BUDG"),
    EP_CMT("EP_CMT"),
    EP_COMMU("EP_COMMU"),
    EP_CONT("EP_CONT"),
    EP_CRIM("EP_CRIM"),
    EP_CRIS("EP_CRIS"),
    EP_CULT("EP_CULT"),
    EP_DELCON("EP_DELCON"),
    EP_DEVE("EP_DEVE"),
    EP_DROI("EP_DROI"),
    EP_ECON("EP_ECON"),
    EP_EMPL("EP_EMPL"),
    EP_ENVI("EP_ENVI"),
    EP_EXTERN_POL("EP_EXTERN_POL"),
    EP_FEMM("EP_FEMM"),
    EP_FINANCE("EP_FINANCE"),
    EP_GROUP_ALDE("EP_GROUP_ALDE"),
    EP_GROUP_ECR("EP_GROUP_ECR"),
    EP_GROUP_EFD("EP_GROUP_EFD"),
    EP_GROUP_EPP("EP_GROUP_EPP"),
    EP_GROUP_GREEN_EFA("EP_GROUP_GREEN_EFA"),
    EP_GROUP_GUE_NGL("EP_GROUP_GUE_NGL"),
    EP_GROUP_SD("EP_GROUP_SD"),
    EP_IMCO("EP_IMCO"),
    EP_IMMU("EP_IMMU"),
    EP_INFRA_LOGIS("EP_INFRA_LOGIS"),
    EP_INNOV("EP_INNOV"),
    EP_INQWOM("EP_INQWOM"),
    EP_INTA("EP_INTA"),
    EP_INTERNAL_POL("EP_INTERNAL_POL"),
    EP_INTERPRET("EP_INTERPRET"),
    EP_ITRE("EP_ITRE"),
    EP_JURI("EP_JURI"),
    EP_LIBE("EP_LIBE"),
    EP_PECH("EP_PECH"),
    EP_PERS("EP_PERS"),
    EP_PETI("EP_PETI"),
    EP_POLI("EP_POLI"),
    EP_PRES("EP_PRES"),
    EP_REGI("EP_REGI"),
    EP_SEDE("EP_SEDE"),
    EP_SG("EP_SG"),
    EP_SURE("EP_SURE"),
    EP_TRAN("EP_TRAN"),
    EP_TRANSL("EP_TRANSL"),
    ERA("ERA"),
    ERC("ERC"),
    ESA("ESA"),
    ESCB("ESCB"),
    ESM("ESM"),
    ESMA("ESMA"),
    ESRB("ESRB"),
    ESTAT("ESTAT"),
    ETF("ETF"),
    EUISS("EUISS"),
    EUMS("EUMS"),
    @XmlEnumValue("EUMS10")
    EUMS_10("EUMS10"),
    @XmlEnumValue("EUMS12")
    EUMS_12("EUMS12"),
    @XmlEnumValue("EUMS15")
    EUMS_15("EUMS15"),
    @XmlEnumValue("EUMS25")
    EUMS_25("EUMS25"),
    @XmlEnumValue("EUMS27")
    EUMS_27("EUMS27"),
    @XmlEnumValue("EUMS6")
    EUMS_6("EUMS6"),
    @XmlEnumValue("EUMS9")
    EUMS_9("EUMS9"),
    @XmlEnumValue("EUMS_EURO11")
    EUMS_EURO_11("EUMS_EURO11"),
    @XmlEnumValue("EUMS_EURO12")
    EUMS_EURO_12("EUMS_EURO12"),
    @XmlEnumValue("EUMS_EURO13")
    EUMS_EURO_13("EUMS_EURO13"),
    @XmlEnumValue("EUMS_EURO15")
    EUMS_EURO_15("EUMS_EURO15"),
    @XmlEnumValue("EUMS_EURO16")
    EUMS_EURO_16("EUMS_EURO16"),
    @XmlEnumValue("EUMS_EURO17")
    EUMS_EURO_17("EUMS_EURO17"),
    @XmlEnumValue("EUMS_NONEURO10")
    EUMS_NONEURO_10("EUMS_NONEURO10"),
    @XmlEnumValue("EUMS_NONEURO11")
    EUMS_NONEURO_11("EUMS_NONEURO11"),
    @XmlEnumValue("EUMS_NONEURO12")
    EUMS_NONEURO_12("EUMS_NONEURO12"),
    @XmlEnumValue("EUMS_NONEURO14")
    EUMS_NONEURO_14("EUMS_NONEURO14"),
    @XmlEnumValue("EUMS_NONEURO3")
    EUMS_NONEURO_3("EUMS_NONEURO3"),
    @XmlEnumValue("EUMS_NONEURO4")
    EUMS_NONEURO_4("EUMS_NONEURO4"),
    EURAG("EURAG"),
    EURATOM("EURATOM"),
    EURCOM("EURCOM"),
    EURCOU("EURCOU"),
    EURCOU_PRES("EURCOU_PRES"),
    EUROCONTROL("EUROCONTROL"),
    EUROFOUND("EUROFOUND"),
    EUROJUST("EUROJUST"),
    EURONEST("EURONEST"),
    EUROPOL("EUROPOL"),
    EURUN("EURUN"),
    EUR_CONVENTON("EUR_CONVENTON"),
    EUSC("EUSC"),
    FAO("FAO"),
    FCH("FCH"),
    FPI("FPI"),
    FRA("FRA"),
    FRONTEX("FRONTEX"),
    FSU("FSU"),
    FUSEN("FUSEN"),
    GATT("GATT"),
    GCEU("GCEU"),
    GIW("GIW"),
    GOVREP("GOVREP"),
    HOME("HOME"),
    HR("HR"),
    HRUFASP("HRUFASP"),
    IAEA("IAEA"),
    IAS("IAS"),
    IBWM("IBWM"),
    ICAO("ICAO"),
    ICCS("ICCS"),
    ICES("ICES"),
    ICRC("ICRC"),
    IDA("IDA"),
    IEEA("IEEA"),
    IES("IES"),
    IGS("IGS"),
    IHCP("IHCP"),
    ILO("ILO"),
    IMI("IMI"),
    INFSO("INFSO"),
    INRO("INRO"),
    INTERPOL("INTERPOL"),
    IPSC("IPSC"),
    IRSG("IRSG"),
    ISOSUGAR("ISOSUGAR"),
    JLS("JLS"),
    JRC("JRC"),
    JRCGEEL("JRCGEEL"),
    JRCISP("JRCISP"),
    JRCKARLS("JRCKARLS"),
    JRCPETT("JRCPETT"),
    JRCSEV("JRCSEV"),
    JUSTI("JUSTI"),
    MARE("MARE"),
    MARKT("MARKT"),
    MOVE("MOVE"),
    NATO("NATO"),
    NP("NP"),
    OAMI("OAMI"),
    OCHA("OCHA"),
    ODCR("ODCR"),
    OIB("OIB"),
    OIL("OIL"),
    OLAF("OLAF"),
    OMB("OMB"),
    OSHA("OSHA"),
    PMO("PMO"),
    PRESS("PRESS"),
    PRESS_COMMUN("PRESS_COMMUN"),
    PUBL("PUBL"),
    RCN("RCN"),
    REA("REA"),
    REGIO("REGIO"),
    RELEX("RELEX"),
    RTD("RTD"),
    SANCO("SANCO"),
    SCIC("SCIC"),
    SCR("SCR"),
    SESAR("SESAR"),
    SG("SG"),
    SJ("SJ"),
    SJ_COMMUN("SJ_COMMUN"),
    SKY("SKY"),
    SPP("SPP"),
    STAT_COMMUN("STAT_COMMUN"),
    TASKF("TASKF"),
    TAXUD("TAXUD"),
    TENTEA("TENTEA"),
    TRADE("TRADE"),
    TREN("TREN"),
    UNECE("UNECE"),
    UNEP("UNEP"),
    UNESCO("UNESCO"),
    UNHCR("UNHCR"),
    UNICEF("UNICEF"),
    UNO("UNO"),
    UNRWA("UNRWA"),
    US_AEC("US_AEC"),
    WFP("WFP"),
    WHO("WHO"),
    WTO("WTO");
    private final String value;

    TCorporatebody(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TCorporatebody fromValue(String v) {
        for (TCorporatebody c: TCorporatebody.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
