//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_interinstitutionalprocedure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_interinstitutionalprocedure"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACC"/&gt;
 *     &lt;enumeration value="ACI"/&gt;
 *     &lt;enumeration value="APP"/&gt;
 *     &lt;enumeration value="AVC"/&gt;
 *     &lt;enumeration value="BUD"/&gt;
 *     &lt;enumeration value="CNB"/&gt;
 *     &lt;enumeration value="CNC"/&gt;
 *     &lt;enumeration value="CNS"/&gt;
 *     &lt;enumeration value="COD"/&gt;
 *     &lt;enumeration value="COS"/&gt;
 *     &lt;enumeration value="DCE"/&gt;
 *     &lt;enumeration value="DEC"/&gt;
 *     &lt;enumeration value="IMM"/&gt;
 *     &lt;enumeration value="INI"/&gt;
 *     &lt;enumeration value="INS"/&gt;
 *     &lt;enumeration value="NLE"/&gt;
 *     &lt;enumeration value="OLP"/&gt;
 *     &lt;enumeration value="ORP"/&gt;
 *     &lt;enumeration value="PRT"/&gt;
 *     &lt;enumeration value="REG"/&gt;
 *     &lt;enumeration value="RPS"/&gt;
 *     &lt;enumeration value="RSO"/&gt;
 *     &lt;enumeration value="RSP"/&gt;
 *     &lt;enumeration value="SLP"/&gt;
 *     &lt;enumeration value="SRP"/&gt;
 *     &lt;enumeration value="SYN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "t_interinstitutionalprocedure", namespace = "http://publications.europa.eu/resource/interinstitutionalprocedures/")
@XmlEnum
public enum TInterinstitutionalprocedure {

    ACC,
    ACI,
    APP,
    AVC,
    BUD,
    CNB,
    CNC,
    CNS,
    COD,
    COS,
    DCE,
    DEC,
    IMM,
    INI,
    INS,
    NLE,
    OLP,
    ORP,
    PRT,
    REG,
    RPS,
    RSO,
    RSP,
    SLP,
    SRP,
    SYN;

    public String value() {
        return name();
    }

    public static TInterinstitutionalprocedure fromValue(String v) {
        return valueOf(v);
    }

}
