//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransmissionExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmissionExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata-transmission}TransmissionExtensionBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sender" type="{urn:eu:ec:cm:common:extensions:v11}ContactType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmissionExtensionType", propOrder = {
    "sender"
})
public class TransmissionExtensionType
    extends TransmissionExtensionBaseType
{

    @XmlElement(required = true)
    protected ContactType sender;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link ContactType }
     *     
     */
    public ContactType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactType }
     *     
     */
    public void setSender(ContactType value) {
        this.sender = value;
    }

}
