//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransmissionRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmissionRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transmission" type="{http://publications.europa.eu/resource/core-metadata-transmission}TransmissionType"/&gt;
 *         &lt;element name="extension" type="{http://publications.europa.eu/resource/core-metadata-transmission}TransmissionRequestExtensionBaseType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmissionRequestType", namespace = "http://publications.europa.eu/resource/core-metadata-transmission", propOrder = {
    "transmission",
    "extension"
})
public class TransmissionRequestType {

    @XmlElement(required = true)
    protected TransmissionType transmission;
    protected List<TransmissionRequestExtensionBaseType> extension;

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionType }
     *     
     */
    public TransmissionType getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionType }
     *     
     */
    public void setTransmission(TransmissionType value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransmissionRequestExtensionBaseType }
     * 
     * 
     */
    public List<TransmissionRequestExtensionBaseType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<TransmissionRequestExtensionBaseType>();
        }
        return this.extension;
    }

}
