//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_resource-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_resource-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACKNOWLEDGE_RECP"/&gt;
 *     &lt;enumeration value="AMEND_PROP"/&gt;
 *     &lt;enumeration value="AMEND_PROP_DEC"/&gt;
 *     &lt;enumeration value="AMEND_PROP_DIR"/&gt;
 *     &lt;enumeration value="AMEND_PROP_REG"/&gt;
 *     &lt;enumeration value="ANNEX"/&gt;
 *     &lt;enumeration value="ANNEX_SUM"/&gt;
 *     &lt;enumeration value="COMMUNIC"/&gt;
 *     &lt;enumeration value="COMMUNIC_POSIT"/&gt;
 *     &lt;enumeration value="CORRIGENDUM"/&gt;
 *     &lt;enumeration value="DATPRO"/&gt;
 *     &lt;enumeration value="DEC"/&gt;
 *     &lt;enumeration value="DEC_DEL"/&gt;
 *     &lt;enumeration value="DEC_DRAFT"/&gt;
 *     &lt;enumeration value="DEC_IMPL"/&gt;
 *     &lt;enumeration value="DIR"/&gt;
 *     &lt;enumeration value="DIR_DEL"/&gt;
 *     &lt;enumeration value="DIR_DRAFT"/&gt;
 *     &lt;enumeration value="DIR_IMPL"/&gt;
 *     &lt;enumeration value="IMPACT_ASSESS"/&gt;
 *     &lt;enumeration value="IMPACT_ASSESS_SUM"/&gt;
 *     &lt;enumeration value="JOINT_COMMUNIC"/&gt;
 *     &lt;enumeration value="JOINT_IMPACT_ASSESS"/&gt;
 *     &lt;enumeration value="JOINT_IMPACT_ASSESS_SUM"/&gt;
 *     &lt;enumeration value="JOINT_PAPER_GREEN"/&gt;
 *     &lt;enumeration value="JOINT_PAPER_WHITE"/&gt;
 *     &lt;enumeration value="JOINT_PROP_DEC"/&gt;
 *     &lt;enumeration value="JOINT_PROP_DIR"/&gt;
 *     &lt;enumeration value="JOINT_PROP_REG"/&gt;
 *     &lt;enumeration value="JOINT_REPORT"/&gt;
 *     &lt;enumeration value="JOINT_SWD"/&gt;
 *     &lt;enumeration value="NOTIF"/&gt;
 *     &lt;enumeration value="OPIN"/&gt;
 *     &lt;enumeration value="OPIN_AMEND_EP"/&gt;
 *     &lt;enumeration value="PAPER_GREEN"/&gt;
 *     &lt;enumeration value="PAPER_WHITE"/&gt;
 *     &lt;enumeration value="PROP_DEC"/&gt;
 *     &lt;enumeration value="PROP_DEC_IMPL"/&gt;
 *     &lt;enumeration value="PROP_DIR"/&gt;
 *     &lt;enumeration value="PROP_DIR_IMPL"/&gt;
 *     &lt;enumeration value="PROP_RECO"/&gt;
 *     &lt;enumeration value="PROP_REG"/&gt;
 *     &lt;enumeration value="PROP_REG_IMPL"/&gt;
 *     &lt;enumeration value="RECO"/&gt;
 *     &lt;enumeration value="RECO_DEC"/&gt;
 *     &lt;enumeration value="RECO_OPIN"/&gt;
 *     &lt;enumeration value="RECO_RECO"/&gt;
 *     &lt;enumeration value="REFERRAL_LET"/&gt;
 *     &lt;enumeration value="REG"/&gt;
 *     &lt;enumeration value="REG_DEL"/&gt;
 *     &lt;enumeration value="REG_IMPL"/&gt;
 *     &lt;enumeration value="REPLY_OPIN_NP"/&gt;
 *     &lt;enumeration value="REPORT"/&gt;
 *     &lt;enumeration value="REPORT_AAR"/&gt;
 *     &lt;enumeration value="REPORT_ANNUAL_DAS"/&gt;
 *     &lt;enumeration value="REPORT_ANNUAL_EDF"/&gt;
 *     &lt;enumeration value="RES_LEGIS"/&gt;
 *     &lt;enumeration value="SWD"/&gt;
 *     &lt;enumeration value="VIEWPOINT"/&gt;
 *     &lt;enumeration value="WORK_DOC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "t_resource-type", namespace = "http://publications.europa.eu/resource/resourcetypes/")
@XmlEnum
public enum TResourceType {

    ACKNOWLEDGE_RECP,
    AMEND_PROP,
    AMEND_PROP_DEC,
    AMEND_PROP_DIR,
    AMEND_PROP_REG,
    ANNEX,
    ANNEX_SUM,
    COMMUNIC,
    COMMUNIC_POSIT,
    CORRIGENDUM,
    DATPRO,
    DEC,
    DEC_DEL,
    DEC_DRAFT,
    DEC_IMPL,
    DIR,
    DIR_DEL,
    DIR_DRAFT,
    DIR_IMPL,
    IMPACT_ASSESS,
    IMPACT_ASSESS_SUM,
    JOINT_COMMUNIC,
    JOINT_IMPACT_ASSESS,
    JOINT_IMPACT_ASSESS_SUM,
    JOINT_PAPER_GREEN,
    JOINT_PAPER_WHITE,
    JOINT_PROP_DEC,
    JOINT_PROP_DIR,
    JOINT_PROP_REG,
    JOINT_REPORT,
    JOINT_SWD,
    NOTIF,
    OPIN,
    OPIN_AMEND_EP,
    PAPER_GREEN,
    PAPER_WHITE,
    PROP_DEC,
    PROP_DEC_IMPL,
    PROP_DIR,
    PROP_DIR_IMPL,
    PROP_RECO,
    PROP_REG,
    PROP_REG_IMPL,
    RECO,
    RECO_DEC,
    RECO_OPIN,
    RECO_RECO,
    REFERRAL_LET,
    REG,
    REG_DEL,
    REG_IMPL,
    REPLY_OPIN_NP,
    REPORT,
    REPORT_AAR,
    REPORT_ANNUAL_DAS,
    REPORT_ANNUAL_EDF,
    RES_LEGIS,
    SWD,
    VIEWPOINT,
    WORK_DOC;

    public String value() {
        return name();
    }

    public static TResourceType fromValue(String v) {
        return valueOf(v);
    }

}
