//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_treaty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_treaty"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACC_1972"/&gt;
 *     &lt;enumeration value="ACC_1973"/&gt;
 *     &lt;enumeration value="ACC_1979"/&gt;
 *     &lt;enumeration value="ACC_1985"/&gt;
 *     &lt;enumeration value="ACC_1994"/&gt;
 *     &lt;enumeration value="ACC_1995"/&gt;
 *     &lt;enumeration value="ACC_2003"/&gt;
 *     &lt;enumeration value="ACC_2005"/&gt;
 *     &lt;enumeration value="ACC_2012"/&gt;
 *     &lt;enumeration value="AMS"/&gt;
 *     &lt;enumeration value="BUDG_1970"/&gt;
 *     &lt;enumeration value="CECA_1951"/&gt;
 *     &lt;enumeration value="CHAR_2007"/&gt;
 *     &lt;enumeration value="CHAR_2010"/&gt;
 *     &lt;enumeration value="EEA"/&gt;
 *     &lt;enumeration value="EURATOM_1957"/&gt;
 *     &lt;enumeration value="EURATOM_2010"/&gt;
 *     &lt;enumeration value="FINAN_1975"/&gt;
 *     &lt;enumeration value="FUSION"/&gt;
 *     &lt;enumeration value="LIS"/&gt;
 *     &lt;enumeration value="LIS_CORR"/&gt;
 *     &lt;enumeration value="NICE"/&gt;
 *     &lt;enumeration value="PRO_ANT"/&gt;
 *     &lt;enumeration value="SCHENGEN"/&gt;
 *     &lt;enumeration value="SEA"/&gt;
 *     &lt;enumeration value="TCONS_2004"/&gt;
 *     &lt;enumeration value="TEC_1992"/&gt;
 *     &lt;enumeration value="TEC_1997"/&gt;
 *     &lt;enumeration value="TEC_2002"/&gt;
 *     &lt;enumeration value="TEC_2006"/&gt;
 *     &lt;enumeration value="TEEC_1957"/&gt;
 *     &lt;enumeration value="TEU_1992"/&gt;
 *     &lt;enumeration value="TEU_1997"/&gt;
 *     &lt;enumeration value="TEU_2002"/&gt;
 *     &lt;enumeration value="TEU_2006"/&gt;
 *     &lt;enumeration value="TEU_2008"/&gt;
 *     &lt;enumeration value="TEU_2010"/&gt;
 *     &lt;enumeration value="TFEU_2008"/&gt;
 *     &lt;enumeration value="TFEU_2010"/&gt;
 *     &lt;enumeration value="TGREENL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "t_treaty", namespace = "http://publications.europa.eu/resource/treaties/")
@XmlEnum
public enum TTreaty {

    ACC_1972,
    ACC_1973,
    ACC_1979,
    ACC_1985,
    ACC_1994,
    ACC_1995,
    ACC_2003,
    ACC_2005,
    ACC_2012,
    AMS,
    BUDG_1970,
    CECA_1951,
    CHAR_2007,
    CHAR_2010,
    EEA,
    EURATOM_1957,
    EURATOM_2010,
    FINAN_1975,
    FUSION,
    LIS,
    LIS_CORR,
    NICE,
    PRO_ANT,
    SCHENGEN,
    SEA,
    TCONS_2004,
    TEC_1992,
    TEC_1997,
    TEC_2002,
    TEC_2006,
    TEEC_1957,
    TEU_1992,
    TEU_1997,
    TEU_2002,
    TEU_2006,
    TEU_2008,
    TEU_2010,
    TFEU_2008,
    TFEU_2010,
    TGREENL;

    public String value() {
        return name();
    }

    public static TTreaty fromValue(String v) {
        return valueOf(v);
    }

}
