//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WorkflowExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata-transmission}WorkflowExtensionBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="workflow_number" type="{urn:eu:ec:cm:common:extensions:v11}WorkflowNumberType" minOccurs="0"/&gt;
 *         &lt;element name="adoption_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="adoption_place" type="{urn:eu:ec:cm:common:extensions:v11}PlaceType" minOccurs="0"/&gt;
 *         &lt;element name="signer_name" type="{urn:eu:ec:cm:common:extensions:v11}NameType" minOccurs="0"/&gt;
 *         &lt;element name="signer_function" type="{urn:eu:ec:cm:common:extensions:v11}FunctionType" minOccurs="0"/&gt;
 *         &lt;element name="greffe_manager" type="{urn:eu:ec:cm:common:extensions:v11}PersonType" minOccurs="0"/&gt;
 *         &lt;element name="delegation" type="{urn:eu:ec:cm:common:extensions:v11}DelegationType" minOccurs="0"/&gt;
 *         &lt;element name="agent_person_list" type="{urn:eu:ec:cm:common:extensions:v11}AgentPersonNameListType" minOccurs="0"/&gt;
 *         &lt;element name="eea_relevance" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="codified_version" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="durability" type="{urn:eu:ec:cm:common:extensions:v11}ConstantType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkflowExtensionType", propOrder = {
    "workflowNumber",
    "adoptionDateTime",
    "adoptionPlace",
    "signerName",
    "signerFunction",
    "greffeManager",
    "delegation",
    "agentPersonList",
    "eeaRelevance",
    "codifiedVersion",
    "durability"
})
public class WorkflowExtensionType
    extends WorkflowExtensionBaseType
{

    @XmlElement(name = "workflow_number")
    protected WorkflowNumberType workflowNumber;
    @XmlElement(name = "adoption_date_time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar adoptionDateTime;
    @XmlElement(name = "adoption_place")
    protected String adoptionPlace;
    @XmlElement(name = "signer_name")
    protected String signerName;
    @XmlElement(name = "signer_function")
    protected String signerFunction;
    @XmlElement(name = "greffe_manager")
    protected PersonType greffeManager;
    protected DelegationType delegation;
    @XmlElement(name = "agent_person_list")
    protected AgentPersonNameListType agentPersonList;
    @XmlElement(name = "eea_relevance")
    protected Boolean eeaRelevance;
    @XmlElement(name = "codified_version")
    protected Boolean codifiedVersion;
    protected String durability;

    /**
     * Gets the value of the workflowNumber property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowNumberType }
     *     
     */
    public WorkflowNumberType getWorkflowNumber() {
        return workflowNumber;
    }

    /**
     * Sets the value of the workflowNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowNumberType }
     *     
     */
    public void setWorkflowNumber(WorkflowNumberType value) {
        this.workflowNumber = value;
    }

    /**
     * Gets the value of the adoptionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAdoptionDateTime() {
        return adoptionDateTime;
    }

    /**
     * Sets the value of the adoptionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAdoptionDateTime(XMLGregorianCalendar value) {
        this.adoptionDateTime = value;
    }

    /**
     * Gets the value of the adoptionPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdoptionPlace() {
        return adoptionPlace;
    }

    /**
     * Sets the value of the adoptionPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdoptionPlace(String value) {
        this.adoptionPlace = value;
    }

    /**
     * Gets the value of the signerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignerName() {
        return signerName;
    }

    /**
     * Sets the value of the signerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignerName(String value) {
        this.signerName = value;
    }

    /**
     * Gets the value of the signerFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignerFunction() {
        return signerFunction;
    }

    /**
     * Sets the value of the signerFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignerFunction(String value) {
        this.signerFunction = value;
    }

    /**
     * Gets the value of the greffeManager property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getGreffeManager() {
        return greffeManager;
    }

    /**
     * Sets the value of the greffeManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setGreffeManager(PersonType value) {
        this.greffeManager = value;
    }

    /**
     * Gets the value of the delegation property.
     * 
     * @return
     *     possible object is
     *     {@link DelegationType }
     *     
     */
    public DelegationType getDelegation() {
        return delegation;
    }

    /**
     * Sets the value of the delegation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelegationType }
     *     
     */
    public void setDelegation(DelegationType value) {
        this.delegation = value;
    }

    /**
     * Gets the value of the agentPersonList property.
     * 
     * @return
     *     possible object is
     *     {@link AgentPersonNameListType }
     *     
     */
    public AgentPersonNameListType getAgentPersonList() {
        return agentPersonList;
    }

    /**
     * Sets the value of the agentPersonList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentPersonNameListType }
     *     
     */
    public void setAgentPersonList(AgentPersonNameListType value) {
        this.agentPersonList = value;
    }

    /**
     * Gets the value of the eeaRelevance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEeaRelevance() {
        return eeaRelevance;
    }

    /**
     * Sets the value of the eeaRelevance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEeaRelevance(Boolean value) {
        this.eeaRelevance = value;
    }

    /**
     * Gets the value of the codifiedVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCodifiedVersion() {
        return codifiedVersion;
    }

    /**
     * Sets the value of the codifiedVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCodifiedVersion(Boolean value) {
        this.codifiedVersion = value;
    }

    /**
     * Gets the value of the durability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurability() {
        return durability;
    }

    /**
     * Sets the value of the durability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurability(String value) {
        this.durability = value;
    }

}
