//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.02 at 01:52:08 PM EEST 
//


package eu2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkflowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="legal_basis_list" type="{http://publications.europa.eu/resource/core-metadata-transmission}LegalBasisListType" minOccurs="0"/&gt;
 *         &lt;element name="addressee_list" type="{http://publications.europa.eu/resource/core-metadata-transmission}AgentListType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://publications.europa.eu/resource/core-metadata-transmission}WorkflowExtensionBaseType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{http://publications.europa.eu/resource/core-metadata}work"/&gt;
 *           &lt;element name="work_reference" type="{http://publications.europa.eu/resource/core-metadata}t_work_ref"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkflowType", namespace = "http://publications.europa.eu/resource/core-metadata-transmission", propOrder = {
    "legalBasisList",
    "addresseeList",
    "extension",
    "workOrWorkReference"
})
public class WorkflowType {

    @XmlElement(name = "legal_basis_list")
    protected LegalBasisListType legalBasisList;
    @XmlElement(name = "addressee_list")
    protected AgentListType addresseeList;
    protected List<WorkflowExtensionBaseType> extension;
    @XmlElements({
        @XmlElement(name = "work", namespace = "http://publications.europa.eu/resource/core-metadata", type = TWork.class),
        @XmlElement(name = "work_reference", type = TWorkRef.class)
    })
    protected List<Object> workOrWorkReference;

    /**
     * Gets the value of the legalBasisList property.
     * 
     * @return
     *     possible object is
     *     {@link LegalBasisListType }
     *     
     */
    public LegalBasisListType getLegalBasisList() {
        return legalBasisList;
    }

    /**
     * Sets the value of the legalBasisList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalBasisListType }
     *     
     */
    public void setLegalBasisList(LegalBasisListType value) {
        this.legalBasisList = value;
    }

    /**
     * Gets the value of the addresseeList property.
     * 
     * @return
     *     possible object is
     *     {@link AgentListType }
     *     
     */
    public AgentListType getAddresseeList() {
        return addresseeList;
    }

    /**
     * Sets the value of the addresseeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentListType }
     *     
     */
    public void setAddresseeList(AgentListType value) {
        this.addresseeList = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkflowExtensionBaseType }
     * 
     * 
     */
    public List<WorkflowExtensionBaseType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<WorkflowExtensionBaseType>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the workOrWorkReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workOrWorkReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkOrWorkReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TWork }
     * {@link TWorkRef }
     * 
     * 
     */
    public List<Object> getWorkOrWorkReference() {
        if (workOrWorkReference == null) {
            workOrWorkReference = new ArrayList<Object>();
        }
        return this.workOrWorkReference;
    }

}
